rem SET PYTHONHOME=%OSGEO4W_ROOT%\apps\Python37
rem SET PYTHONPATH=%PYTHONHOME%;%PYTHONHOME%\Scripts
rem PATH %PYTHONPATH%;%PATH%

SET PYTHONPATH=
SET PYTHONHOME=%OSGEO4W_ROOT%\apps\Python37
PATH %OSGEO4W_ROOT%\apps\Python37;%OSGEO4W_ROOT%\apps\Python37\Scripts;%PATH%
